"""add file_size column to user_reports

Revision ID: bbcc214897f2
Revises: 03f3e212c9d9
Create Date: 2025-07-09 00:57:29.958663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbcc214897f2'
down_revision: Union[str, None] = '03f3e212c9d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_reports', sa.Column('file_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_reports', 'file_size')
    # ### end Alembic commands ###
